from collections import Counter

def generate_file_section_summary(files):
    """Generate a summary of file information"""
    if not files:
        return "<p>No files found.</p>"
    
    formats = get_formats_summary(files)
    access = get_access_summary(files)
    date_range = get_date_range(files)
    derived_from_count = get_derived_from_summary(files)
    generated_by_count = get_generated_by_summary(files)
    
    summary_html = f"""
    <div class="section-summary">
        <h4>Files Summary ({len(files)} items)</h4>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Formats:</div>
                <div class="summary-value">
                    <ul>
                        {''.join(f'<li>{fmt}: {count}</li>' for fmt, count in formats.items())}
                    </ul>
                </div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Access:</div>
                <div class="summary-value">
                    <ul>
                        {''.join(f'<li>{access_type}: {count}</li>' for access_type, count in access.items())}
                    </ul>
                </div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Date Range:</div>
                <div class="summary-value">{date_range}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Provenance:</div>
                <div class="summary-value">
                    <ul>
                        <li>Generated by computation: {generated_by_count}</li>
                        <li>Derived from other files: {derived_from_count}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    """
    
    # Add sample items (first 3)
    if files:
        preview_files = files[:3]
        summary_html += """
        <details>
            <summary>Sample Files</summary>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Format</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
        """
        
        for item in preview_files:
            name = item.get("name", "")
            description = item.get("description", "")
            # Truncate description if too long
            description_display = description
            if len(description) > 100:
                description_display = description[:100] + "..."
            
            format_val = item.get("format", "")
            date = item.get("datePublished", "")
            if not date:
                date = item.get("dateModified", "")
                if not date:
                    date = item.get("dateCreated", "")
            
            summary_html += f"""
            <tr>
                <td>{name}</td>
                <td title="{description}">{description_display}</td>
                <td>{format_val}</td>
                <td>{date}</td>
            </tr>
            """
        
        summary_html += """
                </tbody>
            </table>
        </details>
        """
    
    return summary_html

def get_formats_summary(items):
    """Get a summary of formats in a list of items"""
    formats = [item.get("format", "unknown") for item in items]
    format_counter = Counter(formats)
    return format_counter

def get_access_summary(items):
    """Get a summary of content URL types (available, embargoed, etc.)"""
    access_types = []
    for item in items:
        content_url = item.get("contentUrl", "")
        if not content_url:
            access_types.append("No link")
        elif content_url == "Embargoed":
            access_types.append("Embargoed")
        else:
            access_types.append("Available")
    
    access_counter = Counter(access_types)
    return access_counter

def get_date_range(items):
    """Get the date range for a list of items"""
    dates = []
    for item in items:
        date = item.get("datePublished", "")
        if not date:
            date = item.get("dateModified", "")
            if not date:
                date = item.get("dateCreated", "")
        
        if date:
            dates.append(date)
    
    if not dates:
        return "Unknown"
    
    return f"{min(dates)} to {max(dates)}"

def get_derived_from_summary(items):
    """Get a summary of derived from relationships"""
    derived_counts = 0
    for item in items:
        if "derivedFrom" in item and item["derivedFrom"]:
            derived_counts += 1
    
    return derived_counts

def get_generated_by_summary(items):
    """Get a summary of generated by relationships"""
    generated_counts = 0
    for item in items:
        if "generatedBy" in item and item["generatedBy"]:
            generated_counts += 1
    
    return generated_counts